name: NodeJS with Gulp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run production
    - name: Commit Files
      run: |
        git config --local user.name  ${{ github.actor }}
        git add -A
        git commit -m "Update dist scripts"
    - name: Github Push
      env: ${{ secrets.REPO_GITHUB_TOKEN }}
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.REPO_GITHUB_TOKEN }}
        force: true
        
